server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: eureka1.zdk.com
  client:
    register-with-eureka: true # 表示是否向eureka注册中心注册自己
    fetch-registry: true # 为false表示自己为注册中心
    service-url:  # 监控页面
      defaultZone: http://eureka2.zdk.com:7002/eureka,http://eureka3.zdk.com:7003/eureka